language: ruby
sudo: true
notifications:
  email: false

rvm:
  - 2.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
- curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
- ./run "bundle install && rake loris:run && rake loris:test"